#!/usr/bin/env bash
# generate-compose.sh — emit a docker-compose.yml matching the configured roster.
#
# One service per agent (plus bus + watchdog), all sharing the project bind-mount
# and the .loopy/ runtime. Prints to stdout; redirect to docker-compose.loopy.yml.
set -euo pipefail
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../daemons/common.sh"

emit_service() {
  local name="$1" agent="$2"
  cat <<YAML
  ${name}:
    image: loopy:latest
    build: { context: ., dockerfile: loopy/Dockerfile }
    environment:
      LOOPY_AGENT_ID: "${agent}"
      LOOPY_PROJECT_ROOT: "/work"
      ANTHROPIC_API_KEY: "\${ANTHROPIC_API_KEY:-}"
    volumes:
      - ./:/work
    working_dir: /work
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "loopy/operator/docker-status.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
YAML
}

echo "# Generated by loopy/scripts/generate-compose.sh — roster-specific."
echo "services:"
emit_service bus bus
emit_service watchdog watchdog
while read -r agent; do
  [[ -z "$agent" ]] && continue
  emit_service "${agent/./-}" "$agent"
done < <(loopy_roster)
